language: python

before_install:
  # show a little bit more information about environment
  - sudo apt-get install -y tree
  - env
  - tree
  # install DepHell
  # - curl https://raw.githubusercontent.com/dephell/dephell/master/install.py | /opt/python/3.6/bin/python
  # https://github.com/travis-ci/travis-ci/issues/8589
  - /opt/python/3.6/bin/python install.py
  - dephell inspect self
install:
  - dephell venv create --env=$ENV --python="/opt/python/$TRAVIS_PYTHON_VERSION/bin/python" --level=DEBUG --traceback
  - dephell deps install --env=$ENV --level=DEBUG --traceback
script:
  - dephell venv run --env=$ENV --level=DEBUG --traceback

matrix:
  include:
    - python: "3.5"
      env: ENV=pytest
    - python: "3.6"
      env: ENV=pytest
    - python: "3.7-dev"
      env: ENV=pytest
    - python: "pypy3.5"
      env: ENV=pytest

    # 2.7.15: /usr/local/bin/python
    # 3.6.5:  /usr/local/bin/python3
    - os: osx
      language: generic
      env: ENV=pytest
      before_install:
        - /usr/local/bin/python3 install.py
        - dephell inspect self
      install:
        - dephell venv create --env=$ENV --python=/usr/local/bin/python3 --level=DEBUG --traceback
        - dephell deps install --env=$ENV --level=DEBUG --traceback

    - python: "3.6"
      env: ENV=flake8
