language: python

before_install:
  # show a little bit more information about environment
  - sudo apt-get install -y tree
  - env
  - tree
  # install DepHell
  # - curl https://raw.githubusercontent.com/dephell/dephell/master/install.py | /opt/python/3.6/bin/python
  # https://github.com/travis-ci/travis-ci/issues/8589
  - /opt/python/3.6/bin/python install.py
  - dephell inspect self
install:
  - dephell venv create --env=$ENV --python="/opt/python/$TRAVIS_PYTHON_VERSION/bin/python" --level=DEBUG --traceback
  - dephell deps install --env=$ENV --level=DEBUG --traceback
script:
  - dephell venv run --env=$ENV --level=DEBUG --traceback

matrix:
  include:
    - python: "3.5"
      env: ENV=pytest
    - python: "3.6"
      env: ENV=pytest
    - python: "3.7-dev"
      env: ENV=pytest
    - python: "pypy3.5"
      env: ENV=pytest

    - os: osx
      language: generic
      before_install:
        - which python
        - python --version
        - which python3
        - python3 --version
      env: ENV=pytest

    - python: "3.6"
      env: ENV=flake8
