
# Default section.
# Convert dephell metainfo and dependencies from poetry to setup.py:
# $ dephell deps convert
[tool.dephell.main]
# read from poetry format
from = {format = "poetry", path = "pyproject.toml"}
# and convert into setup.py
to = {format = "setuppy", path = "setup.py"}

# Make lockfile
# $ dephell deps convert --env=lock
[tool.dephell.lock]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "poetrylock", path = "poetry.lock"}

# Install flake8 with plugin in the separated venv and run it:
# $ dephell venv create --env=flake8
# $ dephell deps install --env=flake8
# $ dephell venv run --env=flake8
[tool.dephell.flake8]
# read requirements file
from = {format = "pip", path = "requirements-flake.txt"}
# run this command
command = "flake8"

# Install project dependencies and pytest in the separated venv and run it:
# $ dephell venv create --env=pytest
# $ dephell deps install --env=pytest
# $ dephell venv run --env=pytest
[tool.dephell.pytest]
# read dependencies from setup.py
from = {format = "setuppy", path = "setup.py"}
# install main dependencies and `tests` extra dependencies
envs = ["main", "tests"]
# run command `pytest`
command = "pytest"

# Generate documentation:
# $ dephell venv create --env=docs
# $ dephell deps install --env=docs
# $ dephell venv run --env=docs
[tool.dephell.docs]
# read dependencies from poetry format
from = {format = "poetry", path = "pyproject.toml"}
# install only `docs` extra dependencies
envs = ["docs"]
# run this command:
command = "sphinx-build -M html docs docs/build"

[tool.poetry]
name = "dephell"
version = "0.3.1"
authors = ["Gram <master_fess@mail.ru>"]
description = "Dependency resolution for Python"
readme = "README.md"
license = "MIT"
repository = "https://github.com/dephell/dephell"
keywords = [
    "dephell", "packaging", "dependency", "dependencies", "venv", "licenses",
    "pip", "poetry", "pipfile", "pipenv", "setuptools",
]
# https://pypi.org/classifiers/
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Framework :: Setuptools Plugin",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Topic :: Security",  # because we lock dependencies with hashes :)
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.scripts]
dephell = "dephell.cli:entrypoint"

[tool.poetry.dependencies]
python = ">=3.5"
aiohttp = "*"
appdirs = "*"
attrs = "*"
cerberus = "*"
editorconfig = "*"  # https://github.com/editorconfig/editorconfig-core-py
jinja2 = "*"
m2r = "*"
packaging = "*"
pip = "*"
requests = "*"
tomlkit = "*"
tqdm = "*"

# optional
aiofiles = {optional = true}
autopep8 = {optional = true}
colorama = {optional = true}
graphviz = {optional = true}
yapf = {optional = true}

# dephell ecosystem
dephell_archive = "*"     # https://github.com/dephell/dephell_archive
dephell_discover = "*"    # https://github.com/dephell/dephell_discover
dephell_licenses = "*"    # https://github.com/dephell/dephell_licenses
dephell_links = "*"       # https://github.com/dephell/dephell_links
dephell_markers = "*"     # https://github.com/dephell/dephell_markers
dephell_pythons = "*"     # https://github.com/dephell/dephell_pythons
dephell_shells = "*"      # https://github.com/dephell/dephell_shells
dephell_specifier = "*"   # https://github.com/dephell/dephell_specifier

[tool.poetry.dev-dependencies]
pytest = "*"
sphinx = "*"
recommonmark = "*"
sphinx-rtd-theme = "*"
pygments-github-lexers = "*"

[tool.poetry.extras]
full = ["aiofiles", "autopep8", "colorama", "graphviz", "yapf"]
tests = ["pytest"]
docs = ["sphinx", "recommonmark", "sphinx-rtd-theme", "pygments-github-lexers"]
