[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}

[tool.dephell.egg]
from = {format = "setuppy", path = "setup.py"}
to = {format = "egginfo", path = "."}

[tool.dephell.sdist]
from = {format = "setuppy", path = "setup.py"}
to = {format = "sdist", path = "dist"}

[tool.dephell.flake8]
from = {format = "pip", path = "requirements-flake.txt"}
command = "flake8"

[tool.dephell.pytest]
from = {format = "setuppy", path = "setup.py"}
envs = ["main", "tests"]
command = "pytest"

[tool.poetry]
name = "dephell"
version = "0.3.0"
authors = ["orsinium"]
description = "Dependency resolution for Python"
readme = "README.md"

[tool.poetry.scripts]
dephell = "dephell.cli:entrypoint"

[tool.poetry.dependencies]
python = ">=3.5"
aiofiles = "*"
aiohttp = "*"
appdirs = "*"
attrs = "*"
cerberus = "*"
graphviz = "*"
html2text = "*"
jinja2 = "*"
m2r = "*"
packaging = "*"
pip = "*"
requests = "*"
tomlkit = "*"
tqdm = "*"
yapf = "*"

# dephell ecosystem
dephell_archive = "*"     # https://github.com/dephell/dephell_archive
dephell_discover = "*"    # https://github.com/dephell/dephell_discover
dephell_markers = "*"     # https://github.com/dephell/dephell_markers
dephell_pythons = "*"     # https://github.com/dephell/dephell_pythons
dephell_shells = "*"      # https://github.com/dephell/dephell_shells
dephell_specifier = "*"   # https://github.com/dephell/dephell_specifier

[tool.poetry.dev-dependencies]
pytest = "*"

[tool.poetry.extras]
tests = ["pytest"]
